### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deveyNull**
I added a gitbook to make the course material more accessible.

### CODE REVIEW

**Comment by kazamatzuri** [comment]
that linked book feels  a lot like a link farming site/spammy :/ 
about every second page pushes a 'sign up for the free course' the rest are links to writeups on other pages?

**Comment by deveyNull** [comment]
Not link farming, it's the full content of the course but in a git fork-able format that doesn't require messing around with the actual course website. The links to other writeups are selected because they don't suck (in process of rewriting most of them anyway), but there's plenty of other content in there

**Comment by guijunchen** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
abderrahmaneMustapha, @nxdong, @Duccem, @joiltonrsilva, @msabhii, @AhmedAmio23, @Hulva, @phoenixgao, @Odusanya, @wellingtoncosta, @JimJayLee, @MSVelan, @victorbadaro, @bashier253, @hasnatbabur, @ember-am, @adamzapasnik, @caue-alves, @ctthang, @smorimoto

**Comment by Insaida** [comment]
> here

This post contains a phishing link.

**Comment by Insaida** [comment]
> Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

This post contains a phishing link. 
PLEASE DO NOT CLICK ON THE LINK.

**Comment by deveyNull** [comment]
> > Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.
> 
> This post contains a phishing link. PLEASE DO NOT CLICK ON THE LINK.

Weird that some bot went around and posted phishing links 2 years later, going to kill the thread.

**Pull request closed without merging**
